name: My Pytest Coverage Comment
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  live-test:
    name: Live Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#      - name: Build coverage file
#        run: |
#            set -o pipefail
#            pytest --cov=./ \
#                   --junitxml=pytest.xml \
#                   --capture=tee-sys \
#                   --cov-report=term-missing:skip-covered | \
#            tee pytest-coverage.txt

      - name: Build coverage file
        run: |
            pytest --cov=./ --junitxml=tests/pytest.xml --cov-report 'xml:tests/coverage.xml'
            more tests/pytest.xml
            more tests/coverage.xml
      - name: Check the output coverage
        run: |
          echo "Coverage Percantage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
          echo "Summary Report - ${{ steps.coverageComment.outputs.summaryReport }}"

          echo "Coverage Warnings - ${{ steps.coverageComment.outputs.warnings }}"

          echo "Coverage Errors - ${{ steps.coverageComment.outputs.errors }}"
          echo "Coverage Failures - ${{ steps.coverageComment.outputs.failures }}"
          echo "Coverage Skipped - ${{ steps.coverageComment.outputs.skipped }}"
          echo "Coverage Tests - ${{ steps.coverageComment.outputs.tests }}"
          echo "Coverage Time - ${{ steps.coverageComment.outputs.time }}"
          echo "Not Success Test Info - ${{ steps.coverageComment.outputs.notSuccessTestInfo }}"

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./tests/coverage.xml
          junitxml-path: ./tests/pytest.xml
          coverage-path-prefix: ./tests/
